# Database settings
spring.datasource.url=jdbc:h2:mem:coursedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# H2 Console settings
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate & SQL initialization
# ????? update ??????? Hibernate ???????? ??????? ???????????
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
# ??????????? ????????? SQL, ???? Hibernate ?? ???????? ?????
spring.jpa.defer-datasource-initialization=true

# Show SQL in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true