# ?????? ???????????? ??
spring.datasource.url=jdbc:h2:file:./data/coursedb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# ????????? ??????? H2 (???????? ???????)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ???????????? Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never